stages:
- build
- cleanup_build

build_colorphone:
  stage: build
  script:
  - commit_msg=$(git log --format=%B -n 1)
  - echo $commit_msg
  - mkdir outputs
  - if [[ $commit_msg == *"[BuildAllDebug]"* ]] || [[ $commit_msg == *"Merge branch"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneDebug
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorphone/debug/*.apk outputs/
  - fi
  - if [[ $commit_msg == *"[BuildColorPhone]"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneRelease
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorphone/release/*.apk outputs/
  -   cp app/build/outputs/mapping/colorphone/release/mapping.txt outputs/
  - fi
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /^\[Build.*/
  artifacts:
    paths:
    - outputs/build-dependencies.txt
    - outputs/*.apk
    - outputs/mapping.txt

    expire_in: 1 week
  tags:
  - android

build_colorflash:
  stage: build
  script:
  - commit_msg=$(git log --format=%B -n 1)
  - echo $commit_msg
  - mkdir outputs
  - if [[ $commit_msg == *"[BuildAllDebug]"* ]] || [[ $commit_msg == *"Merge branch"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorflashDebug
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorflash/debug/*.apk outputs/
  - fi
  - if [[ $commit_msg == *"[BuildColorFlash]"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorflashRelease
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorflash/release/*.apk outputs/
  -   cp app/build/outputs/mapping/colorflash/release/mapping.txt outputs/
  - fi
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /^\[Build.*/
  artifacts:
    paths:
    - outputs/build-dependencies.txt
    - outputs/*.apk
    - outputs/mapping.txt

    expire_in: 1 week
  tags:
  - android

cleanup_build_job:
    stage: cleanup_build
    script:
    - ./gradlew clean
    - ./rm -r outputs
    when: on_failure
    tags:
    - android
