stages:
- build
- cleanup_build

build_toutiao:
  stage: build
  script:
  - commit_msg=$(git log --format=%B -n 1)
  - echo $commit_msg
  - mkdir outputs
  - if [[ $commit_msg == *"[BuildAllDebug]"* ]] || [[ $commit_msg == *"Merge branch"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneJinritoutiaoDebug
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/olorphoneJinritoutiao/debug/*.apk outputs/
  - fi
  - if [[ $commit_msg == *"[BuildToutiao]"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneJinritoutiaoRelease
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorphoneJinritoutiao/release/*.apk outputs/
  -   cp app/build/outputs/mapping/colorphoneJinritoutiao/release/mapping.txt outputs/
  - fi
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /^\[Build.*/
  artifacts:
    paths:
    - outputs/build-dependencies.txt
    - outputs/*.apk
    - outputs/mapping.txt

    expire_in: 1 week
  tags:
  - android

build_yingyongbao:
  stage: build
  script:
  - commit_msg=$(git log --format=%B -n 1)
  - echo $commit_msg
  - mkdir outputs
  - if [[ $commit_msg == *"[BuildAllDebug]"* ]] || [[ $commit_msg == *"Merge branch"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneYingyongbaoDebug
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorphoneYingyongbao/debug/*.apk outputs/
  - fi
  - if [[ $commit_msg == *"[BuildYingyongbao]"* ]]; then
  -   git submodule update --init
  -   ./gradlew :app:assembleColorphoneYingyongbaoRelease
  -   ./gradlew -p . :app:dependencies > outputs/build-dependencies.txt
  -   cp app/build/outputs/apk/colorphoneYingyongbao/release/*.apk outputs/
  -   cp app/build/outputs/mapping/colorphoneYingyongbao/release/mapping.txt outputs/
  - fi
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /^\[Build.*/
  artifacts:
    paths:
    - outputs/build-dependencies.txt
    - outputs/*.apk
    - outputs/mapping.txt

    expire_in: 1 week
  tags:
  - android

cleanup_build_job:
    stage: cleanup_build
    script:
    - ./gradlew clean
    - ./rm -r outputs
    when: on_failure
    tags:
    - android
