libCommons:
  RemoteConfig:
    PlistServerEnabled: false
    PlistFile: "HSRemoteConfig.sp"
    PlistUrl: ""
  ImageCache:
    CacheSize: 0
  Analytics:
    EnableFlurry: false
    EnableAppsFlyer: false
    FlurryKey: "SMVNPB98M59Z86TB2HZ7"
    FlurryStoredMaxCount: 1000
    FacebookID: ""
    TapjoySDKKey: ""
    FlyerKey: ""
    FlyerEvents:
      - "App_Open_New"
      - "App_Open_New_NonOrganic"
      - "Call_Assistant_Can_Show"
  Market:
    3rdChannel: "YYB_ORG_None_None_None"
    DefaultMarket: "Google"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
  AppID: "21344708"
  Connection:
    SigKey: "K5079383"
    HashKey: "/}#$-WbLZg)/3WD2F=SUj!?h!<D*|zi}"
    InnerConnectEnable: false
  Umeng:
    AppKey: "5c651326f1f5562281001958"
    Channel: "YYB_ORG_None_None_None"
    PushKey: "b93a2a1069e4044452cf3b72c7ad15eb"

libFramework:
  Alerts:
    LocalFile: "alerts.sp"
    RemoteUrl: "http://cdn.ihandysoft.cn/light2019/apps/apkcolorphone/alerts/yyb_alerts_colorphone_1.0.0.sp"
  Push:
    SenderID: ""
    SendTokenToServer: false

Application:
  CashCenterURL: "https://service.atcloudbox.com/cashcenter"
  PushServiceHost: "http://service.atcloudbox.com"
  CmGameHost: "https://hcldx-xyx-sdk-svc.beike.cn"
  CmGameId: "huancailaidianxiu"