libCommons:
  RemoteConfig:
    PlistServerEnabled: true
    PlistFile: "HSRemoteConfig.sp"
    PlistUrl: ""
  ImageCache:
    CacheSize: 0
  Analytics:
    EnableFlurry: true
    EnableAppsFlyer: true
    FlurryKey: ""
    FlurryStoredMaxCount: 1000
    FacebookID: ""
    TapjoySDKKey: ""
    FlyerKey: "d4VKN2yBPk7gqTRBZcwkbc"
    FlyerEvents:
      - "App_Open_New"
      - "App_Open_New_NonOrganic"
      - "Call_Assistant_Can_Show"
      - "colorphone_retention_day1"
  Market:
    3rdChannel: "APK_TT_TT_None_None"
    DefaultMarket: "Google"
    Markets:
      Google:
        AppPackage: "com.android.vending"
        AppUrl: "market://details?id="
        WebUrl: "https://play.google.com/store/apps/details?id="
  Domain: "https://service.atcloudbox.com"
  AppID: "21344708"
  Connection:
    SigKey: "K5079383"
    HashKey: "/}#$-WbLZg)/3WD2F=SUj!?h!<D*|zi}"
  Umeng:
    AppKey: "5c651326f1f5562281001958"
    Channel: "APK_TT_TT_None_None"
    PushKey: "b93a2a1069e4044452cf3b72c7ad15eb"

libFramework:
  Alerts:
    LocalFile: "alerts.sp"
    RemoteUrl: "http://cdn.appcloudbox.net/launcherapps/apps/launcher/alerts/launcher-1.3.6-alerts.la//TODO For pm to replace when release new version"

Application:
  CashCenterURL: "https://service.atcloudbox.com/cashcenter"
  CmGameHost: "https://hcldx-xyx-sdk-svc.beike.cn"
  CmGameId: "huancailaidianxiu"